publish:
  whoami: master
notifications:
  commits:      notifications@ignite.apache.org
  issues:       notifications@ignite.apache.org
  pullrequests: notifications@ignite.apache.org
github:
  description: "Apache Ignite 3 Website"
  homepage: https://ignite.apache.org/
  labels:
    - distributed-sql-database
    - iot
    - network-client
    - ignite
    - data-management-platform
    - big-data
    - cloud
    - database
    - network-server
    - sql
    - cache
    - in-memory-computing
    - in-memory-database
  features:
    wiki: false
    issues: false
    projects: false
    discussions: false
  enabled_merge_buttons:
    squash:  true
    squash_commit_message: PR_TITLE
    merge:   false
    rebase:  false
  protected_branches:
    main:
      required_linear_history: true
      required_signatures: false
      required_conversation_resolution: true
  autolink_jira:
    - IGNITE
